import { useEffect, useState } from 'react'
import { ArrowLeft, Database, LogOut, MessageSquare, RefreshCw, ShieldCheck, Users } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import { supabase } from '../lib/supabase'
import type { Conversation, ConversationMember, Message, Profile } from '../types/database'

export default function AdminPage() {
  const { user, signOut } = useAuth(); const navigate = useNavigate(); const [profiles, setProfiles] = useState<Profile[]>([]); const [conversations, setConversations] = useState<Conversation[]>([]); const [members, setMembers] = useState<ConversationMember[]>([]); const [messages, setMessages] = useState<Message[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const isAdmin = user?.app_metadata?.role === 'admin'
  const load = async () => { setLoading(true); setError(''); const [profileResult, conversationResult, memberResult, messageResult] = await Promise.all([supabase.from('profiles').select('*').order('created_at', { ascending: false }), supabase.from('conversations').select('*').order('updated_at', { ascending: false }), supabase.from('conversation_members').select('*'), supabase.from('messages').select('*').order('created_at', { ascending: false })]) ; if (profileResult.error || conversationResult.error || memberResult.error || messageResult.error) setError('Admin data could not be loaded. Verify the admin claim and migration.'); setProfiles(profileResult.data || []); setConversations(conversationResult.data || []); setMembers(memberResult.data || []); setMessages(messageResult.data || []); setLoading(false) }
  useEffect(() => { if (isAdmin) load() }, [isAdmin])
  if (!isAdmin) return <main className="admin-denied"><ShieldCheck size={35}/><h1>Admin access required</h1><p>Your account does not have the administrator role.</p><button className="primary-button" onClick={() => navigate('/chats')}>Return to chats</button></main>
  return <div className="admin-shell"><header className="admin-header"><div className="admin-brand"><span className="brand-mark"><ShieldCheck size={17}/></span><span><b>Tandem</b><small>Admin console</small></span></div><div className="admin-actions"><button onClick={load} aria-label="Refresh data"><RefreshCw size={17}/></button><button onClick={() => navigate('/chats')}><ArrowLeft size={17}/> Chats</button><button onClick={async () => { await signOut(); navigate('/login') }}><LogOut size={17}/> Log out</button></div></header><main className="admin-content"><div className="admin-title"><div><p className="eyebrow">Restricted workspace</p><h1>Everything, in one view.</h1><p className="muted">Operational visibility across Tandem's live data.</p></div><span className="admin-badge"><ShieldCheck size={15}/> Administrator</span></div>{error && <div className="error">{error}</div>}<section className="admin-stats"><Stat icon={<Users/>} label="Profiles" value={profiles.length}/><Stat icon={<MessageSquare/>} label="Messages" value={messages.length}/><Stat icon={<Database/>} label="Conversations" value={conversations.length}/><Stat icon={<Users/>} label="Memberships" value={members.length}/></section><section className="admin-grid"><div className="admin-panel"><div className="panel-heading"><h2>People</h2><span>{profiles.length} total</span></div>{loading ? <p className="muted">Loading...</p> : <div className="admin-table">{profiles.map(profile => <div className="admin-row" key={profile.id}><span className="admin-avatar">{profile.display_name.slice(0,1).toUpperCase()}</span><span><b>{profile.display_name}</b><small>@{profile.username}</small></span><em className={profile.status === 'online' ? 'online-label' : ''}>{profile.status || 'offline'}</em><time>{new Date(profile.created_at).toLocaleDateString()}</time></div>)}</div>}</div><div className="admin-panel"><div className="panel-heading"><h2>All messages</h2><span>{messages.length} total</span></div><div className="admin-table">{messages.map(message => <div className="admin-message" key={message.id}><div><b>{profiles.find(p => p.id === message.sender_id)?.display_name || 'Unknown user'}</b><time>{new Date(message.created_at).toLocaleString()}</time></div><p className={message.deleted_at ? 'deleted-text' : ''}>{message.deleted_at ? 'Message deleted' : message.content}</p><small>{message.conversation_id}</small></div>)}</div></div></section></main></div> }
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="admin-stat"><span>{icon}</span><small>{label}</small><strong>{value}</strong></div> }
